# Generated by Django 2.2 on 2019-08-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppelFond', '0002_auto_20190806_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tappelfonds',
            name='compte_numero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tappelfonds',
            name='numero_recharge',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('MANAGER', 'MANAGER'), ('CLIENT', 'CLIENT')], max_length=50, null=True),
        ),
    ]
