# Generated by Django 2.2 on 2019-08-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppelFond', '0003_auto_20190806_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tappelfonds',
            name='compte_numero',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tappelfonds',
            name='numero_recharge',
            field=models.CharField(max_length=30),
        ),
    ]
