# Generated by Django 2.2 on 2019-08-10 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppelFond', '0005_user_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_staff',
            new_name='staff',
        ),
    ]
