# Generated by Django 2.2 on 2019-08-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppelFond', '0008_auto_20190810_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='user', max_length=15),
        ),
    ]
