# Generated by Django 2.2 on 2019-08-12 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppelFond', '0010_auto_20190810_1358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbanque',
            options={},
        ),
        migrations.RenameField(
            model_name='tbanque',
            old_name='code_banq',
            new_name='code_banque',
        ),
        migrations.RenameField(
            model_name='tbanque',
            old_name='nom_banq',
            new_name='nom_banque',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.AlterModelTable(
            name='tbanque',
            table=None,
        ),
    ]
